Repository andela/mrm_api, pull requests merged in 2019-09, with the labels that each got.

#491 CON-284 Update a structure node
  api/office_structure/schema.py
  fixtures/office_structure/update_node_fixtures.py
  tests/test_office_structure/test_update_node.py
Labels: peer review

#496 CON-299 Fix deleted room device
  api/room/models.py
Labels: peer review

#494 CON-211 Fix meeting room issue on staging
  api/events/schema.py
  api/room/schema_query.py
  fixtures/room/query_room_fixtures.py
  tests/test_rooms/test_query_rooms.py
Labels: Ready for Review

#497 CON-303 Create timezone and country type for Kigali location
  alembic/versions/ace641b9b89b_create_timezone_countrytype_rwanda.py
  api/location/models.py
Labels: To be merged
