Repository andela/mrm_api, pull requests merged in 2019-08, with the labels that each got.

#470 CON-171 Send email to invitees when event is auto-canceled
  helpers/email/email.py
Labels: peer review

#475 CON-207 Display backend logs through http
  app.py
  tests/base.py
  tests/test_logs/__init__.py
  tests/test_logs/test_logs_endpoint.py
  utilities/file_reader.py
Labels: Read for Review, to be merged

#481 CON-243 Fix the display of logs
  app.py
  docker/prod/mrm_api.conf
  utilities/file_reader.py
Labels: peer review

#478 CON 213 Refactor user authentication module
  fixtures/role/role_fixtures.py
  fixtures/user/delete_user.py
  helpers/auth/authentication.py
  tests/base.py
  tests/test_role/test_query_role.py
Labels: peer review

#479 CON-212 Add timestamps fields to database records
  alembic/versions/964435a2570d_add_create_and_update_timestamps_on_all_.py
  helpers/database.py
Labels: peer review

#484 CON 254 Implement functionality to enable users set their location
  api/user/schema.py
  fixtures/user/user_fixture.py
  helpers/auth/authentication.py
  tests/test_user/test_set_user_location.py
Labels: Ready for Review

#485 CON-252 Delete node by its id
  api/office_structure/schema.py
  fixtures/office_structure/delete_office_structure_fixtures.py
  tests/test_office_structure/test_delete_node.py
Labels: Ready for Review, To be merged

#472 CON-199 Set up jenkins pipeline for the backend application
  jenkins/Jenkinsfile
  jenkins/KubernetesPod.yml
  jenkins/scripts/build_image.sh
  jenkins/scripts/codeclimate_reports.sh
  jenkins/scripts/codeclimate_results.sh
  jenkins/scripts/create_test_db.sh
  jenkins/scripts/deploy_backend_to_kubernetes.sh
  jenkins/scripts/mock_test_data.sh
  jenkins/scripts/notify_slack.sh
  jenkins/scripts/run_tests.sh
  jenkins/scripts/set_env_vars.sh
  jenkins/scripts/setup_gcloud.sh
  jenkins/scripts/upload_coverage.sh
Labels: Ready for Review

#471 CON-168 Restrict an admin from creating super admins.
  api/user/schema.py
  fixtures/analytics/query_all_analytics_fixtures.py
  fixtures/role/role_fixtures.py
  fixtures/user/user_fixture.py
  helpers/user_role/__init__.py
  helpers/user_role/restrict_admin.py
  tests/base.py
  tests/test_analytics/test_all_analytics_query.py
  tests/test_logs/test_logs_endpoint.py
  tests/test_user/test_change_user_role.py
Labels: Ready for Review

#482 CON-200 Prevent users from having multiple roles
  api/user/schema.py
  fixtures/user_role/user_role_fixtures.py
  tests/test_user/test_create_user.py
  tests/test_user_roles/test_create_user_role.py
Labels: Ready for Review

#489 CON-243 Fix log configuration error
  docker/prod/mrm_api.conf
Labels: peer review

#490 CON-285 Fix error when deleted user tries to set their location
  api/user/schema.py
  helpers/auth/authentication.py
  tests/base.py
  tests/test_analytics/test_all_analytics_query.py
Labels: Ready for Review
